sudo: required

services:
    - docker

language: python

python:
    - "2.7"

env:
    - TIKA_VER=1.15
      TIKA_APP_JAR=/tmp/tika-app-${TIKA_VER}.jar 
      FAUP_PATH=/tmp/faup 
      ZEMANA_PATH=/tmp/zemana 
      DOCKER_ROOT_PATH=/tmp/docker-root 
      DOCKER_ELASTICSEARCH_PATH=/tmp/docker-elasticsearch

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential cmake libfuzzy-dev unrar spamassassin
    
    # Build latest images spamscope-root, spamscope-elasticsearch

    # make images
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        git clone -b $TRAVIS_BRANCH --single-branch https://github.com/SpamScope/spamscope-dockerfile-root.git $DOCKER_ROOT_PATH;
        cd $DOCKER_ROOT_PATH;
        docker build -t $DOCKER_USERNAME/spamscope-root .;
        cd -;
        
        # Unitests in Docker container
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'python tests/attachments.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'python tests/test_attachments_post_processing.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'python tests/test_attachments_utils.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'python tests/test_bitmap.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'python tests/test_network_post_processing.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'python tests/test_spamassassin.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'python tests/test_utils.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'thug -V';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'spamscope-topology -v';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root /bin/sh -c 'spamscope-elasticsearch -v';
                
        git clone -b $TRAVIS_BRANCH --single-branch https://github.com/SpamScope/spamscope-dockerfile-elasticsearch.git $DOCKER_ELASTICSEARCH_PATH;
        cd $DOCKER_ELASTICSEARCH_PATH; 
        docker build -t $DOCKER_USERNAME/spamscope-elasticsearch .;
        cd -;
      fi
      
    - if [ "$TRAVIS_BRANCH" == "develop" ]; then
        git clone -b $TRAVIS_BRANCH --single-branch https://github.com/SpamScope/spamscope-dockerfile-root.git $DOCKER_ROOT_PATH;
        cd $DOCKER_ROOT_PATH;
        docker build -t $DOCKER_USERNAME/spamscope-root:develop .;
        cd -;
        
        # Unitests in Docker container
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'python tests/attachments.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'python tests/test_attachments_post_processing.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'python tests/test_attachments_utils.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'python tests/test_bitmap.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'python tests/test_network_post_processing.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'python tests/test_spamassassin.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'python tests/test_utils.py';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'thug -V';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'spamscope-topology -v';
        docker run --rm -it $DOCKER_USERNAME/spamscope-root:develop /bin/sh -c 'spamscope-elasticsearch -v';
        
        git clone -b $TRAVIS_BRANCH --single-branch https://github.com/SpamScope/spamscope-dockerfile-elasticsearch.git $DOCKER_ELASTICSEARCH_PATH;
        cd $DOCKER_ELASTICSEARCH_PATH;
        docker build -t $DOCKER_USERNAME/spamscope-elasticsearch:develop .;
        cd -;
      fi

# command to install dependencies
install: 
    - pip install -r requirements.txt && python setup.py install
    - git clone https://$BITBUCKET_USER:$BITBUCKET_ROBOT_KEY@bitbucket.org/$BITBUCKET_USER/zemana-api.git $ZEMANA_PATH;
      cd $ZEMANA_PATH && python setup.py install && cd -
    - src/cli/faup.sh
    - cd ${FAUP_PATH}/src/lib/bindings/python && python setup.py install && cd -

before_script:
    - curl -o ${TIKA_APP_JAR} https://archive.apache.org/dist/tika/tika-app-${TIKA_VER}.jar

# command to run tests
script: 
    # Unittests
    - python tests/test_attachments.py
    - python tests/test_attachments_post_processing.py
    - python tests/test_attachments_utils.py
    - python tests/test_bitmap.py
    - python tests/test_utils.py
    - python tests/test_spamassassin.py

    # cli help
    - spamscope-elasticsearch -h
    - spamscope-topology -h

    # timing
    - cd tests && python timing_test_search_keywords.py && cd -

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push $DOCKER_USERNAME/spamscope-root;
        docker push $DOCKER_USERNAME/spamscope-elasticsearch;
      fi
    - if [ "$TRAVIS_BRANCH" == "develop" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push $DOCKER_USERNAME/spamscope-root:develop;
        docker push $DOCKER_USERNAME/spamscope-elasticsearch:develop;
      fi

notifications:
    slack: spamscope:$SLACK_KEY
